project/models/bp_directorio.py
from project import db
from project.models.bp_upload import Imagen


rubro_producto = db.Table('rubro_producto',
                        db.Column('rubro_id', db.Integer, db.ForeignKey('rubros.id')),
                        db.Column('producto_id', db.Integer, db.ForeignKey('productos.id'))
                        )



productor_producto = db.Table('productor_producto',
                        db.Column('productor_id', db.Integer, db.ForeignKey('productores.id')),
                        db.Column('producto_id', db.Integer, db.ForeignKey('productos.id'))
                        )



class Productor(db.Model):

    __tablename__ = 'productores'

    id = db.Column(db.Integer, primary_key=True)
    nombre_fantasia = db.Column(db.String, nullable=False)
    razon_social = db.Column(db.String, nullable=False)
    website = db.Column(db.String)
    productos = db.relationship('Producto', secondary= productor_producto, back_populates='productores')
    imagenes = db.relationship('Imagen', back_populates='productor')

    def __init__(self, nombre_fantasia, razon_social, website=None):
        self.nombre_fantasia = nombre_fantasia
        self.razon_social = razon_social
        self.website= website

    def __repr__(self):
        return '<Productor {}>'.format(self.nombre_fantasia)
    

class Producto(db.Model):

    __tablename__ = 'productos'
    
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(60), nullable=False)
    productores = db.relationship('Productor', secondary= productor_producto, back_populates='productos')
    rubros = db.relationship('Rubro', secondary = rubro_producto, back_populates = 'productos')

    def __init__(self, nombre):
        self.nombre = nombre

    def __repr__(self):
        return '<Producto: {}>'.format(self.nombre)



class Rubro(db.Model):

    __tablename__ = 'rubros'
    
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(60), nullable=False)
    productos = db.relationship('Producto', secondary= rubro_producto, back_populates='rubros')

    def __init__(self, nombre):
        self.nombre = nombre

    def __repr__(self):
        return '<Rubro: {}>'.format(self.nombre)

project/bp_directorio/forms.py
# project/catalogo/forms.py
from flask_wtf import Form

from wtforms import  SelectField, SubmitField


from project.models import *



class ElegirRubroForm(Form):
    rubro= SelectField(u'', choices=[], coerce=int)
    
    #submit = SubmitField()

project/bp_directorio/__init__.py
# project/catalogo/__init__.py

from flask import Blueprint

bp = Blueprint('bp_directorio', __name__)

from project.bp_directorio import routes

project/bp_directorio/routes.py
from flask import Flask, render_template, request, flash

from project import db
from project.models.bp_directorio import *
from project.bp_directorio import bp
from .forms import ElegirRubroForm



@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    form = ElegirRubroForm()
    entries = db.session.query(Productor).all()
    form.rubro.choices = [(rubro.id, rubro.nombre) for rubro in Rubro.query.all()]
    form.rubro.choices.insert(0,(0, 'Selecciona el rubro'))
    if request.method == "POST":
    	id_rubro = request.form['rubro']
    	entries = db.session.query(Productor).join(Productor, Producto.productores).join(Rubro, Producto.rubros).filter(Rubro.id==id_rubro).all()
    	return render_template('bp_directorio/index.html', entries=entries, form=form)

    return render_template('bp_directorio/index.html',entries=entries, form= form)

project/templates/bp_directorio/index.html
  

{% extends "base.html" %}
{% from '_formhelpers.html' import render_field %}

    {% block content %}


  <form class="form-inline" action="{{ url_for('bp_directorio.index') }}" method="POST" role="form">

    {{ form.hidden_tag()  }}
    {% for field in form if field.type not in ["HiddenField", "CSRFTokenField"] %}
    <div class="form-group">
      {{ render_field(field) }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Ver</button>
  </form>
<br>
            


{%if entries %}
<table class="table table-hover">

  <tbody>
    {% for entry in entries%}
    <tr class="d-flex">

      <td class="col-1">{% for imagen in entry.imagenes %}
        <img src="{{imagen.path}}" alt="imagen.name" width="80">
        {%endfor%}    
      </td>
      <td class="col-8">                    <span>
        <a href="https://www.google.cl">{{ entry.nombre_fantasia}}</a>
      </span>
      <br>
      <span>We specialize in offering an unparalleled street art and graffiti experience with our art gallery shows, team building activities, graphic design and murals, and retail boutique.... En el nom
        {%if entry.productos %}          
        {% for producto in entry.productos %}
        {{ producto.nombre }}
        {% endfor %}
        {%endif%}&nbsp;
      </span>
      <span></span></td>
      <td class="col-3">
        <br>
        <span>Direccion linea 1</span>
        <br>
        <span>Comuna&nbsp;</span>
        <span>,&nbsp;</span>
        <span>Region&nbsp;</span>
        <span>94103</span>
        <br>
        <span>United States</span>
        <br>
        <span>Phone:&nbsp;</span>
        <span>(+56) 9 9223 1568</span>
        <br>
        <span>
          {%if entry.productos %}
          <a href="{{ entry.website}}" target="_blank">Website</a>
          {%endif%}
        &nbsp;</span>
        <span><a href="mailto:1AM@email.com">Email</a>&nbsp;</span>
        <span></span>
      </td>
    </tr>
    {% else %}
    <p>No entries yet. Add some!</p>
    {% endfor %}
  </tbody>
</table>

{%endif%}
{% endblock %}