project/models/bp_auth.py
from project import db

from datetime import datetime 


#models/auth.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy import Column, Integer, String, Table, ForeignKey
from sqlalchemy.orm import sessionmaker, relationship, backref
from sqlalchemy.ext.associationproxy import association_proxy

from hashlib import md5
# Local Imports
from project import db, login

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    is_admin = db.Column(db.Boolean, default=False)

    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
            return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password) 

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest, size)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

project/bp_auth/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, TextAreaField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo,  Length
from project.models.bp_auth import User

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    #submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    #submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    #submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

project/bp_auth/__init__.py
#auth/__init__.py

from flask import Blueprint

bp = Blueprint('bp_auth', __name__)

from project.bp_auth import routes

project/bp_auth/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, session, request
from flask_login import login_required, current_user, login_user, logout_user
from werkzeug.urls import url_parse

from project.bp_auth import bp
from project import db

from project.models.bp_auth import User

from .forms import LoginForm, RegistrationForm, EditProfileForm

from functools import wraps

def admin_required(f):
    @wraps(f)
    def decorator(*args, **kwargs):
    	#if current_user.role not in ([Role.admin,]):
    	if current_user.is_authenticated and not current_user.is_admin:
    		flash('Insufficient privilige for user'.format(current_user.username))
    		next_page = request.args.get('next')
    		if not next_page:
    			next_page = url_for('bp_directorio.index')
    		return redirect(next_page)
    		#return redirect(url_for('bp_directorio.index'))
    	return f(*args, **kwargs)
    return decorator


@bp.before_request
def before_request():
	if current_user.is_authenticated:
		current_user.last_seen = datetime.utcnow()
		db.session.commit()

@bp.route("/")
@login_required
def index():
	return redirect(url_for('bp_directorio.index'))


@bp.route('/login', methods=['GET', 'POST'])
def login():
	title='Sign In'
	if current_user.is_authenticated:
		return redirect(url_for('bp_directorio.index'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()
		if user is None or not user.check_password(form.password.data):
			flash('Invalid username or password')
			return redirect(url_for('bp_auth.login'))
		remember_me = False
		#remember_me=form.remember_me.data
		login_user(user, remember=remember_me)
		next_page = request.args.get('next')
		if not next_page:
			next_page = url_for('bp_directorio.index')
		return redirect(next_page)
	return render_template('bp_auth/login.html', title=title, form=form)



@bp.route('/logout')
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('bp_directorio.index'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
	title='Register'
	if current_user.is_authenticated:
		return redirect(url_for('bp_directorio.index'))
	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(username=form.username.data, email=form.email.data)
		user.set_password(form.password.data)
		db.session.add(user)
		db.session.commit()
		flash('Congratulations, you are now a registered user!')
		return redirect(url_for('bp_auth.login'))
	return render_template('bp_auth/register.html', title=title, form=form)


@bp.route('/user/<username>')
@login_required
def user(username):
	title='Ver perfil'
	user = User.query.filter_by(username=username).first_or_404()
	return render_template('bp_auth/user.html', title=title, user=user)



@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
	title='Actualiza tu perfil'
	form = EditProfileForm(current_user.username)
	if form.validate_on_submit():
		current_user.username = form.username.data
		current_user.about_me = form.about_me.data
		db.session.commit()
		flash('Your changes have been saved.')
		return redirect(url_for('bp_auth.user', username=current_user.username))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.about_me.data = current_user.about_me
	return render_template('bp_auth/edit_profile.html', title=title,
		form=form)

project/templates/bp_auth/edit_profile.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
  <h1>Edit Profile</h1>

<form class="form" action="{{ url_for('bp_auth.edit_profile') }}" method="POST" role="form">
	{{ form.hidden_tag()  }}
	{% for field in form if field.type not in ["HiddenField", "CSRFTokenField"] %}
	{{ render_field(field) }}
	{% endfor %}

	<input class="btn btn-primary" type="submit" value="Enviar">
</form>

{% endblock content %}

project/templates/bp_auth/login.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block content %}

 <h1>Login</h1>
<form class="form" action="{{ url_for('bp_auth.login', next=request.args.get('next')) }}" method="POST" role="form">
	{{ form.hidden_tag()  }}
	{% for field in form if field.type not in ["HiddenField", "CSRFTokenField"] %}
	{{ render_field(field) }}
	{% endfor %}

	<input class="btn btn-primary" type="submit" value="Enviar">

</form>
<hr>
<p>New User? <a href="{{ url_for('bp_auth.register') }}">Click to Register!</a></p>

{% endblock content %}

project/templates/bp_auth/register.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block content %}

 <h1>Register</h1>
<form class="form" action="{{ url_for('bp_auth.register') }}" method="POST" role="form">
	{{ form.hidden_tag()  }}
	{% for field in form if field.type not in ["HiddenField", "CSRFTokenField"] %}
	{{ render_field(field) }}
	{% endfor %}


	<input class="btn btn-primary" type="submit" value="Enviar">
</form>

{% endblock content %}

project/templates/bp_auth/user.html
{% extends "base.html" %}

{% block content %}

    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td>
                <h1>User: {{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}<p>Last seen on: {{ user.last_seen }}</p>{% endif %}
            </td>
        </tr>
    </table>

                    {% if user == current_user %}
                <p><a href="{{ url_for('bp_auth.edit_profile') }}">Edit your profile</a></p>
                {% endif %}
{% endblock %}